name: Freight4u
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.2

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  awesome_bottom_bar: ^1.2.4
  gap: ^3.0.1
  flutter_rating_bar: ^4.0.1
  dio: ^5.8.0+1
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^18.0.1
  shimmer: ^3.0.0
  url_launcher: ^6.3.1
  intl: ^0.20.2
  geolocator: ^13.0.2
  shared_preferences: ^2.5.2
  stacked: ^3.4.4
  file_picker: ^10.1.9
  permission_handler: ^12.0.0+1
  signature: ^6.0.0
  markdown_widget: ^2.3.2+8
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.3
  firebase_core: ^3.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
      - assets/images/logo.png
      - assets/images/login.png
      - assets/images/profile.jpg
      - assets/images/inductiontext1.jpg
      - assets/images/inductiontext2.jpg
      - assets/images/
      # - assets/icons/
      # - assets/fonts/
      # - assets/strings/
      # - assets/animations/
      # - assets/lottie/
      # - assets/svgs/


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/freight-logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
